rh_common_pkgs: "sshpass,cifs-utils,nfs-utils,lsof,elfutils-libelf-devel,glibc-headers,glibc-devel,rpcbind,xfsprogs,kernel-devel,jq,expect,net-tools"
rh_common_devel_pkgs: "git"
# libxml2-python,s3cmd

rh7_common_devel_pkgs: "make,perl,gcc,tcl,tk,libnl"
rh8_common_devel_pkgs: "make,perl,gcc,tcl,tk,libnl3,python2,python2-libselinux"
rh9_common_devel_pkgs: "make,perl,gcc,tcl,tk,libnl3,yum-utils,firewalld,python3-libselinux,python3,python3-libselinux,libselinux-python3,python3-policycoreutils,policycoreutils-python-utils,iproute-tc,container-selinux,chrony,jq,java-1.8.0-openjdk,yum-plugin-versionlock,python3-pexpect"

rh_docker_pkgs: "docker-ce,docker-ce-cli,containerd.io,docker-compose-plugin,docker-scan-plugin,container-selinux"
# libcgroup,libcgroup-tools

suse_common_pkgs: "sshpass,cifs-utils,nfs-utils,lsof,glibc-devel,rpcbind,xfsprogs,kernel-devel,jq,expect,net-tools,restorecond,policycoreutils,setools-console"
suse_common_devel_pkgs: "git"
# libxml2-python,s3cmd
suse15_common_devel_pkgs: "make,perl,gcc,tcl,tk,firewalld,python3,python3-policycoreutils,policycoreutils-python-utils,chrony,jq,python3-pexpect"
suse_docker_pkgs: "docker,containerd,conntrack-tools"    # packages for container engine
suse_extra_pkgs: "selinux-policy-targeted,selinux-policy-devel,libseccomp-devel,libcgroup-tools,libcgroup1,cpuset,libcpuset1,cni,cni-plugins"

# suse_kube_pkgs: "cri-o,cri-tools,kubernetes-kubeadm,kubernetes-client,docker"
# suse_kube_pkgs: "docker,containerd,kubernetes-kubeadm,kubernetes-client"
# suse_kube_pkgs: "cri-o,cri-tools,kubernetes-kubeadm,kubernetes-client,podman"
# suse_docker_pkgs: "docker-ce,docker-ce-cli,containerd.io,docker-compose-plugin,docker-scan-plugin,container-selinux"
# libcgroup,libcgroup-tools


# libnl,elfutils-libelf-devel,kernel-devel
ubt_common_pkgs: "sshpass,s3cmd,cifs-utils,nfs-client,libnl-*,elfutils*,lsof,rpcbind,glibc-*,xfsprogs,linux-headers-generic,jq,expect,nvme-cli,selinux-utils"
ubt_common_devel_pkgs: "git,make,gcc,tcl,tk"

ubt20_common_devel_pkgs: "perl,python3-pexpect"
ubt22_common_devel_pkgs: "perl,python3-pexpect"
ubt23_common_devel_pkgs: "perl,python3-pexpect"

ubt_docker_pkgs: "docker.io,containerd"

official_rh_pkgs: "pdsh"
official_ubt_pkgs: "pdsh"

update_cache: false
upgrade_packages: false
