---
# Deploy and Destroy Jenkins with Metallb
- name: Check OS ( Kubernetes )
  fail: msg="Not a Red Hat or SUSE based System!"
  when: ansible_os_family != 'RedHat' or  ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky' or ansible_os_family != 'openSUSE Leap'


- name: Set Facts for Rabbitmq
  import_tasks: set-rabbitmq-facts.yml
  tags:
    - install
    - uninstall
  # when: inventory_hostname in groups['master']


- name: Apply Kernel Parameters for rabbitmq
  import_tasks: apply-rabbitmq-kernel-parameters.yml
  tags: install


- name: Enable Helm Repository
  import_tasks: enable-helm-repo.yml
  tags: install
  when: _helm.enable_repo == true and inventory_hostname in groups['master']


#- name: Install Metallb
#  import_tasks: install-metallb.yml
#  tags: install
#  when: metallb.install == true and inventory_hostname in groups['master']


#- name: Install Cert Manager
#  import_tasks: install-cert-manager.yml
#  tags: install
#  when: cert_manager.install == true and inventory_hostname in groups['master']


- name: Install Kustomize
  import_tasks: install-kustomize.yml
  tags: install
  when: _kustomize.install == true and inventory_hostname in groups['master']


- name: Deploy rabbitmq
  import_tasks: install-rabbitmq.yml
  tags: install
  when: (( rabbitmq is defined and rabbitmq == true ) or ( rabbitmq_all is defined and rabbitmq_all == true )) and inventory_hostname in groups['master']


#- name: Install Load Balancer
#  import_tasks: install-lb.yml
#  tags: install
#  when: metallb.install == true and inventory_hostname in groups['master']


#- name: Uninstall Load Balancer
#  import_tasks: uninstall-lb.yml
#  tags: uninstall
#  when: metallb.install == true and inventory_hostname in groups['master']


- name: Destroy Rabbitmq
  import_tasks: uninstall-rabbitmq.yml
  tags: uninstall
  when: (( rabbitmq is defined and rabbitmq == true ) or ( rabbitmq_all is defined and rabbitmq_all == true )) and inventory_hostname in groups['master']


#- name: Uninstall Cert Manager
#  import_tasks: uninstall-cert-manager.yml
#  tags: uninstall
#  when: cert_manager.install == true and inventory_hostname in groups['master']


#- name: Uninstall Metallb
#  import_tasks: uninstall-metallb.yml
#  tags: uninstall
#  when: metallb.install == true and inventory_hostname in groups['master']


- name: Disable Helm Repository
  import_tasks: disable-helm-repo.yml
  tags: uninstall
  when: _helm.enable_repo == true and inventory_hostname in groups['master']


- name: Remove Kernel Parameters
  import_tasks: remove-rabbitmq-kernel-parameters.yml
  tags: uninstall
  when: (( rabbitmq is defined and rabbitmq == true ) or ( rabbitmq_all is defined and rabbitmq_all == true )) and inventory_hostname in groups['master']


