---
- name: Create Directory for Persistent Volumes
  file:
    path: "{{ _awx.storage_path }}-{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  register: create_pv_dir
  with_sequence: start=0 end={{ total_awx_containers|int }}
- debug: msg={{ create_pv_dir }}
  when: print_debug == true


- name: Apply Kernel Parameters for awx
  lineinfile:
    dest: /etc/sysctl.d/sysctl-k8s.conf
    line: "{{ item }}"
    state: present
  register: apply_kernel_parameters
  with_items:
    - "{{ _awx.kernel_parameters }}"
  notify:
    - Reload Sysctl
- debug: msg={{ apply_kernel_parameters }}
  when: print_debug == true


