---
base_path: /root

_argocd:
  install: true
  major_version: 7
  minor_version: 0
  patch_version: 0
  build_version:
  namespace: argocd
  storage_class: "argocd-storage"
  storage_path: "/mnt/argocd-storage"
  replica: 3
  db:
    name: "argocd"
    user: "jomoon"
    password: "changeme"
  root_password: "changeme"
  mariabackup_password: "changeme"
  k8s:
    major_version: 1
    minor_version: 29
    patch_version: 0
    build_version:
  hostname: "argocd.jtest.pivotal.io"
  service:
    metadata:
      name: argocd-loadbalancer
      namespace: argocd
  ingress:
    metadata:
      name: argocd-ingress
      namespace: nginx-ingress
    hostname: "argocd.jtest.pivotal.io"
  kernel_parameters:
    - "net.ipv4.neigh.default.gc_thresh1 = 0"       # For ARP Cache
  lb:
    install: true
    ip_addr: "192.168.1.219"


_helm:
  enable_repo: true
  major_version: 3
  minor_version:
  patch_version:
  build_version:


_cm:
  install: false
  major_version: 1
  minor_version: 7
  patch_version: 1

