base_path: /root


_kustomize:
  install: true
  download_url: "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"
  major_version: 5
  minor_version: 4
  patch_version: 2


_elasticsearch:
  install: true
  major_version:
  minor_version:
  patch_version:
  build_version:
  admin_user: "admin"
  admin_password: "changeme"
  admin_email: "rokmc756@gmail.com"
  enable_discovery_daemon: false
  clone_git: true
  nvme: true
  namespace: elasticsearch
  storage_path: "/mnt/elasticsearch-storage"
  storage_class: "elasticsearch-storage"
  k8s:
    major_version: 1
    minor_version: 28
    patch_version: 0
    build_version:
  hostname: "elastic.jtest.pivotal.io"
  service:
    metadata:
      name: elasticsearch-loadbalancer
      namespace: elasticsearch
  ingress:
    metadata:
      name: elasticsearch-ingress
      namespace: elasticsearch
    hostname: "elastic.jtest.pivotal.io"
  kernel_parameters:
    - "net.ipv4.neigh.default.gc_thresh1 = 0"   # For ARP Cache
    - "fs.inotify.max_user_instances=2280"
    - "fs.inotify.max_user_watches=755360"
  elasticsearch:
    install: true
    replica: 3
    ip_addr: "192.168.1.219"
  filebeat:
    install: true
    replica: 3
    ip_addr: "192.168.1.220"
  logstash:
    install: true
    replica: 3
    ip_addr: "192.168.1.221"
  kibana:
    install: true
    replica: 3
    ip_addr: "192.168.1.222"


total_elasticsearch_containers: "{{ _elasticsearch.elasticsearch.replica|int + _elasticsearch.logstash.replica|int }}"


_helm:
  enable_repo: true
  major_version: 3
  minor_version:
  patch_version:
  build_version:


_nginx:
  ingress:
    install: true
    name: nginx-ingress
    class_name: elasticsearch-ingress-class
    namespace: "nginx-ingress"
    major_version:
    minor_version:
    patch_version:
    hostname: elastic
    domain: jtest.pivotal.io
    service: kibana-kibana
    ip_addr: "192.168.1.222"
    port: 5601       # Kibana Port
  k8s_ingress:
    major_version: 3
    minor_version: 0
    patch_version: 2


_ssl:
  dir: "{{ base_path }}/elasticsearch-certs"
  days: 3660
  country: "KR"
  state: "Seoul"
  location: "Guro"
  organization: "Pivotal"
  common_name: "jest.pivotal.io"
  email: "rokmc756@gmail.com"


