base_path: /root


_kustomize:
  install: false
  download_url: "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"
  major_version: 5
  minor_version: 4
  patch_version: 2


_kafka:
  install: true
  major_version: 27
  minor_version: 1
  patch_version: 2
  build_version:
  admin_user: "admin"
  admin_password: "Changeme123"
  admin_email: "rokmc756@gmail.com"
  enable_discovery_daemon: false
  clone_git: false
  namespace: kafka
  storage_path: "/mnt/kafka-storage"
  storage_class: "kafka-storage"
  k8s:
    major_version: 1
    minor_version: 29
    patch_version: 0
    build_version:
  hostname: "kafka.jtest.pivotal.io"
  service:
    metadata:
      name: kafka-loadbalancer
      namespace: kafka
  ingress:
    metadata:
      name: kafka-ingress
      namespace: kafka
    hostname: "kafka.jtest.pivotal.io"
  kernel_parameters:
    - "net.ipv4.neigh.default.gc_thresh1 = 0"   # For ARP Cache
    - "fs.inotify.max_user_instances=2280"
    - "fs.inotify.max_user_watches=755360"
  lb:
    install: true
    ip_addr: "192.168.1.221"
  controller:
    replica: 4
  broker:
    replica: 4
  zookeeper:
    enabled: false
    replica: 3
  kraft:
    enabled: false


total_kafka_containers: "{{ _kafka.controller.replica|int + _kafka.broker.replica|int }}"


_kafka_ui:
  install: true
  major_version: 0
  minor_version: 7
  patch_version: 6
  build_version:
  namespace: kafka-ui
  repo_name: kafka-ui
  download_link: "https://provectus.github.io/kafka-ui-charts"
  replica: 1
  lb:
    install: true
    ip_addr: "192.168.1.219"


_kafdrop:
  install: true
  namespace: kafka
  replica: 1
  lb:
    install: true
    ip_addr: "192.168.1.223"


_helm:
  enable_repo: true
  major_version: 3
  minor_version:
  patch_version:
  build_version:


_nginx:
  ingress:
    install: true
    name: nginx-ingress
    class_name: kafka-ui-ingress-class
    namespace: "nginx-ingress"
    major_version:
    minor_version:
    patch_version:
    hostname: kafka
    domain: jtest.pivotal.io
    ip_addr: "192.168.1.219"
    replica: 1
  k8s_ingress:
    major_version: 3
    minor_version: 0
    patch_version: 2


_ssl:
  dir: "{{ base_path }}/kafka-ui-certs"
  days: 3660
  country: "KR"
  state: "Seoul"
  location: "Guro"
  organization: "Pivotal"
  common_name: "jest.pivotal.io"
  email: "rokmc756@gmail.com"

