# https://oopflow.medium.com/setup-install-rancher-onto-existing-kubernetes-cluster-for-high-availability-7351f0284592

- name: Download and Install Helm
  shell: |
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    chmod 755 get_helm.sh
    ./get_helm.sh
  register: install_helm
  args:
    chdir: "{{ base_path }}/"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg={{ install_helm }}


- name: Add NGINX Helm Repo
  shell: |
    helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
  register: add_nginx_helm_repo
  args:
    chdir: "{{ base_path }}/"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg={{ add_nginx_helm_repo }}


- name: Add Bitnami Helm Repo
  shell: |
    helm repo add bitnami https://charts.bitnami.com/bitnami
  register: add_bitnami_helm_repo
  args:
    chdir: "{{ base_path }}/"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg={{ add_bitnami_helm_repo }}


- name: Add Jetstack Helm Repo
  shell: |
    helm repo add jetstack https://charts.jetstack.io
  register: add_jetstack_helm_repo
  args:
    chdir: "{{ base_path }}/"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg={{ add_jetstack_helm_repo }}


- name: Update Helm Repo
  shell: |
    helm repo update
  register: update_helm_repo
  args:
    chdir: "{{ base_path }}/"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg={{ update_helm_repo }}

