# https://github.com/kubeflow/pipelines/issues/6121
- name: Load Kernel Modules for KubeFlow
  shell: |
    modprobe {{ item }}
  with_items:
    - nf_nat
    - xt_REDIRECT
    - xt_owner
    - iptable_nat
    - iptable_mangle
    - iptable_filter


- name: Create Directory for Persistent Volumes
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  register: create_pv_dir
  with_items:
    - "/mnt/authservice-storage"
    - "/mnt/katib-storage"
- debug: msg={{ create_pv_dir }}
  when: print_debug == true


- name: Delete GPFS Backends Package
  package:
    name: gvfs-backends
    state: absent
  register: delete_gvfs_backends_pkg
- debug: msg={{ delete_gvfs_backends_pkg }}
  when: print_debug == true


- name: Apply Kernel Parameters for Metallb and ML Pipeline
  lineinfile:
    dest: /etc/sysctl.d/sysctl-k8s.conf
    line: "{{ item }}"
    state: present
  register: apply_kernel_parameters
  with_items:
    - "{{ _kubeflow.kernel_parameters }}"
  notify:
    - Reload Sysctl
- debug: msg={{ apply_kernel_parameters }}
  when: print_debug == true

